(()=>{
 const serviceData=[
  {detail:`<div class="work-object"><div class="work-stack"><div class="work-node"><b>真实任务</b><span>样本、责任人与结果</span></div><div class="work-node"><b>关键未知</b><span>先验证最重要的不确定性</span></div></div><div class="work-link"></div><div class="work-agent">项目设计<small>Scope</small></div><div class="work-link"></div><div class="work-stack"><div class="work-node"><b>验证标准</b><span>可核对、可复现</span></div><div class="work-node"><b>首期边界</b><span>继续 / 调整 / 停止</span></div></div></div><div class="service-guardrails"><span>任务准入</span><span>评测设计</span><span>项目边界</span></div><a class="service-more-v1" href="#">了解更多 →</a>`},
  {detail:`<div class="work-object"><div class="work-stack"><div class="work-node"><b>知识材料</b><span>文档、知识库、历史记录</span></div><div class="work-node"><b>业务系统</b><span>ERP、CRM、现有工具</span></div></div><div class="work-link"></div><div class="work-agent">AI<small>Agent</small></div><div class="work-link"></div><div class="work-stack"><div class="work-node"><b>人工确认</b><span>关键节点由人把关</span></div><div class="work-node"><b>输出结果</b><span>可追溯、可衡量、可迭代</span></div></div></div><div class="service-guardrails"><span>权限控制</span><span>证据来源</span><span>效果评估</span><span>持续优化</span></div><a class="service-more-v1" href="#">了解更多 →</a>`},
  {detail:`<div class="work-object"><div class="work-stack"><div class="work-node"><b>多系统</b><span>合同、订单、财务、资料</span></div><div class="work-node"><b>多角色</b><span>业务、财务、供应商、管理者</span></div></div><div class="work-link"></div><div class="work-agent">上下文<small>Context</small></div><div class="work-link"></div><div class="work-stack"><div class="work-node"><b>处理依据</b><span>材料与判断可追溯</span></div><div class="work-node"><b>协同状态</b><span>谁在处理、处理到哪</span></div></div></div><div class="service-guardrails"><span>证据归集</span><span>角色协同</span><span>过程留痕</span></div><a class="service-more-v1" href="#">了解更多 →</a>`}
 ];
 const opts=[...document.querySelectorAll('.service-option')];
 function activateService(i){opts.forEach((el,n)=>{const on=n===i;el.classList.toggle('is-active',on);el.setAttribute('aria-selected',on?'true':'false');const d=el.querySelector('.service-detail');if(d){d.innerHTML=on?serviceData[n].detail:'';d.setAttribute('aria-hidden',on?'false':'true')}})}
 opts.forEach((el,i)=>{el.addEventListener('click',()=>activateService(i));el.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse') activateService(i)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateService(i)}if(e.key==='ArrowRight'){e.preventDefault();activateService((i+1)%opts.length);opts[(i+1)%opts.length].focus()}if(e.key==='ArrowLeft'){e.preventDefault();activateService((i+opts.length-1)%opts.length);opts[(i+opts.length-1)%opts.length].focus()}})});
 activateService(1);
 const tabs=[...document.querySelectorAll('.project-tab')],panes=[...document.querySelectorAll('.project-pane')];
 function activateProject(i){tabs.forEach((t,n)=>t.classList.toggle('is-active',n===i));panes.forEach((p,n)=>p.classList.toggle('is-active',n===i))}
 tabs.forEach((t,i)=>t.addEventListener('click',()=>activateProject(i)));
})();